#!/bin/bash
shopt -s expand_aliases
source ~/.bashrc
isabelle build -v -d . -b paraTheory_Session
isabelle build -v -d . -b n_flash_base_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__1_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__2_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__3_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__4_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__5_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__6_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__7_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__8_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__9_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__10_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__11_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__12_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__13_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__14_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__15_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__16_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__17_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__18_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__19_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__20_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__21_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__22_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__23_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__24_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__25_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__26_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__27_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__28_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__29_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__30_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__31_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__32_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__33_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__34_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__35_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__36_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__37_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__38_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__39_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__40_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__41_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__42_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__43_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__44_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__45_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__46_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__47_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__48_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__49_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__50_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__51_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__52_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__53_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__54_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__55_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__56_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__57_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__58_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__59_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__60_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__61_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__62_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__63_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__64_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__65_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__66_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__67_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__68_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__69_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__70_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__71_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__72_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__73_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__74_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__75_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__76_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__77_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__78_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__79_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__80_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__81_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__82_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__83_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__84_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__85_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__86_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__87_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__88_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__89_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__90_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__91_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__92_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__93_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__94_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__95_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__96_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__97_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__98_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__99_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__100_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__101_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__102_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__103_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__104_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__105_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__106_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__107_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__108_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__109_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__110_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__111_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__112_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__113_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__114_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__115_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__116_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__117_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__118_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__119_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__120_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__121_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__122_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__123_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__124_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__125_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__126_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__127_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__128_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__129_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__130_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__131_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__132_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__133_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__134_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__135_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__136_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__137_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__138_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__139_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__140_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__141_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__142_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__143_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__144_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__145_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__146_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__147_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__148_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__149_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__150_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__151_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__152_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__153_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__154_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__155_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__156_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__157_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__158_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__159_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__160_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__161_Session
isabelle build -v -d . -b n_flash_lemma_on_inv__162_Session
isabelle build -v -d . -b n_flash_lemma_invs_on_rules_Session
isabelle build -v -d . -b n_flash_invs_on_inis_Session
isabelle build -v -d . -b n_flash_Session
