#!/bin/bash
shopt -s expand_aliases
source ~/.bashrc
isabelle build -v -d . -b paraTheory_Session
isabelle build -v -d . -b n_german_base_Session
isabelle build -v -d . -b n_german_lemma_on_inv__1_Session
isabelle build -v -d . -b n_german_lemma_on_inv__2_Session
isabelle build -v -d . -b n_german_lemma_on_inv__3_Session
isabelle build -v -d . -b n_german_lemma_on_inv__4_Session
isabelle build -v -d . -b n_german_lemma_on_inv__5_Session
isabelle build -v -d . -b n_german_lemma_on_inv__6_Session
isabelle build -v -d . -b n_german_lemma_on_inv__7_Session
isabelle build -v -d . -b n_german_lemma_on_inv__8_Session
isabelle build -v -d . -b n_german_lemma_on_inv__9_Session
isabelle build -v -d . -b n_german_lemma_on_inv__10_Session
isabelle build -v -d . -b n_german_lemma_on_inv__11_Session
isabelle build -v -d . -b n_german_lemma_on_inv__12_Session
isabelle build -v -d . -b n_german_lemma_on_inv__13_Session
isabelle build -v -d . -b n_german_lemma_on_inv__14_Session
isabelle build -v -d . -b n_german_lemma_on_inv__15_Session
isabelle build -v -d . -b n_german_lemma_on_inv__16_Session
isabelle build -v -d . -b n_german_lemma_on_inv__17_Session
isabelle build -v -d . -b n_german_lemma_on_inv__18_Session
isabelle build -v -d . -b n_german_lemma_on_inv__19_Session
isabelle build -v -d . -b n_german_lemma_on_inv__20_Session
isabelle build -v -d . -b n_german_lemma_on_inv__21_Session
isabelle build -v -d . -b n_german_lemma_on_inv__22_Session
isabelle build -v -d . -b n_german_lemma_on_inv__23_Session
isabelle build -v -d . -b n_german_lemma_on_inv__24_Session
isabelle build -v -d . -b n_german_lemma_on_inv__25_Session
isabelle build -v -d . -b n_german_lemma_on_inv__26_Session
isabelle build -v -d . -b n_german_lemma_on_inv__27_Session
isabelle build -v -d . -b n_german_lemma_on_inv__28_Session
isabelle build -v -d . -b n_german_lemma_on_inv__29_Session
isabelle build -v -d . -b n_german_lemma_on_inv__30_Session
isabelle build -v -d . -b n_german_lemma_on_inv__31_Session
isabelle build -v -d . -b n_german_lemma_on_inv__32_Session
isabelle build -v -d . -b n_german_lemma_on_inv__33_Session
isabelle build -v -d . -b n_german_lemma_on_inv__34_Session
isabelle build -v -d . -b n_german_lemma_on_inv__35_Session
isabelle build -v -d . -b n_german_lemma_on_inv__36_Session
isabelle build -v -d . -b n_german_lemma_on_inv__37_Session
isabelle build -v -d . -b n_german_lemma_on_inv__38_Session
isabelle build -v -d . -b n_german_lemma_on_inv__39_Session
isabelle build -v -d . -b n_german_lemma_on_inv__40_Session
isabelle build -v -d . -b n_german_lemma_on_inv__41_Session
isabelle build -v -d . -b n_german_lemma_on_inv__42_Session
isabelle build -v -d . -b n_german_lemma_on_inv__43_Session
isabelle build -v -d . -b n_german_lemma_on_inv__44_Session
isabelle build -v -d . -b n_german_lemma_on_inv__45_Session
isabelle build -v -d . -b n_german_lemma_on_inv__46_Session
isabelle build -v -d . -b n_german_lemma_on_inv__47_Session
isabelle build -v -d . -b n_german_lemma_on_inv__48_Session
isabelle build -v -d . -b n_german_lemma_on_inv__49_Session
isabelle build -v -d . -b n_german_lemma_on_inv__50_Session
isabelle build -v -d . -b n_german_lemma_on_inv__51_Session
isabelle build -v -d . -b n_german_lemma_on_inv__52_Session
isabelle build -v -d . -b n_german_lemma_invs_on_rules_Session
isabelle build -v -d . -b n_german_invs_on_inis_Session
isabelle build -v -d . -b n_german_Session
